data:extend({
	{
		type = "recipe",
		name = "delivery-cannon-chest",
		result = "delivery-cannon-chest",
		enabled = false,
		energy_required = 10,
		ingredients = {
			{ "radar", 1 },
			{ "steel-chest", 10 },
			{ "concrete", 20 },
		},
		requester_paste_multiplier = 1,
		always_show_made_in = false,
	},
	{
		type = "item",
		name = "delivery-cannon-chest",
		icon = "__delivery-cannon__/graphics/icons/delivery-cannon-chest.png",
		icon_size = 64,
		order = "j-b",
		subgroup = "logistic-network",
		stack_size = 50,
		place_result = "delivery-cannon-chest",
	},
	{
		type = "container",
		name = "delivery-cannon-chest",
		icon = "__delivery-cannon__/graphics/icons/delivery-cannon-chest.png",
		icon_size = 64,
		flags = { "placeable-neutral", "player-creation" },
		minable = { mining_time = 0.5, result = "delivery-cannon-chest"},
		max_health = 1000,
		corpse = "big-remnants",
		dying_explosion = "medium-explosion",
		collision_box = { { -1.3, -1.3 }, { 1.3, 1.3 } },
		collision_mask = {
			"water-tile",
			"item-layer",
			"object-layer",
			"player-layer",
		},
		selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
		se_allow_in_space = true,
		inventory_size = 40,
		resistances = {
			{ type = "explosion", percent = 75 },
			{ type = "impact", percent = 90 },
			{ type = "fire", percent = 90 },
		},
		open_sound = { filename = "__base__/sound/metallic-chest-open.ogg", volume = 0.65 },
		close_sound = { filename = "__base__/sound/metallic-chest-close.ogg", volume = 0.7 },
		vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
		picture = {
			layers = {
				{
					filename = "__delivery-cannon__/graphics/entity/delivery-cannon/delivery-cannon-chest.png",
					frame_count = 1,
					line_length = 1,
					width = 208 / 2,
					height = 200 / 2,
					shift = { 0, 0 },
					hr_version = {
						filename = "__delivery-cannon__/graphics/entity/delivery-cannon/hr-delivery-cannon-chest.png",
						frame_count = 1,
						line_length = 1,
						width = 208,
						height = 200,
						shift = { 0, 0 },
						scale = 0.5,
					},
				},
				{
					draw_as_shadow = true,
					filename = "__delivery-cannon__/graphics/entity/delivery-cannon/delivery-cannon-chest-shadow.png",
					frame_count = 1,
					line_length = 1,
					width = 278 / 2,
					height = 150 / 2,
					shift = { 0.5625, 0.5875 },
					hr_version = {
						draw_as_shadow = true,
						filename = "__delivery-cannon__/graphics/entity/delivery-cannon/hr-delivery-cannon-chest-shadow.png",
						frame_count = 1,
						line_length = 1,
						width = 278,
						height = 150,
						shift = { 0.5625, 0.5875 },
						scale = 0.5,
					},
				},
			}
		},
		circuit_wire_connection_point = {
			shadow = { red = {0.7, -1.3}, green = {0.7, -1.3}, },
			wire = { red = {0.7, -1.3}, green = {0.7, -1.3}, }
		},
		circuit_wire_max_distance = 12.5,
	},
})